"""
Comprehensive master company registry for the job-agent project.

All collectors use the same company universe. A collector first tries the
ATS-specific override, then falls back to a normalized version of the company
name. Missing boards should return no jobs and be skipped by the collector.

The registry deliberately prioritizes risk, fraud, AI, fintech, bureaus,
consulting, banking, insurance, enterprise technology, and auto finance.
"""

from __future__ import annotations

import re
import unicodedata
from typing import Iterable


COMPANY_GROUPS = {'risk_fraud_identity': ['FICO',
                         'Feedzai',
                         'Socure',
                         'Featurespace',
                         'BioCatch',
                         'Sift',
                         'Sardine',
                         'Alloy',
                         'DataVisor',
                         'Quantexa',
                         'ComplyAdvantage',
                         'NICE Actimize',
                         'Provenir',
                         'Zest AI',
                         'Amount',
                         'Forter',
                         'Riskified',
                         'Signifyd',
                         'DataDome',
                         'Arkose Labs',
                         'Fingerprint',
                         'SEON',
                         'Unit21',
                         'Chainalysis',
                         'TRM Labs',
                         'Elliptic',
                         'Hawk AI',
                         'Resistant AI',
                         'Silent Eight',
                         'ThetaRay',
                         'Salv',
                         'Napier AI',
                         'Fenergo',
                         'Sumsub',
                         'Jumio',
                         'Trulioo',
                         'Persona',
                         'Prove Identity',
                         'Mitek',
                         'Entrust',
                         'CLEAR',
                         'Early Warning Services',
                         'Ekata',
                         'IDology',
                         'ThreatMetrix',
                         'LexisNexis Risk Solutions',
                         'LexisNexis Reed Tech',
                         'Verafin',
                         'Fraud.net',
                         'Kount',
                         'SentiLink',
                         'Ocrolus',
                         'Inscribe',
                         'Reality Defender',
                         'Pindrop',
                         'BehavioSec',
                         'Fortress Identity',
                         'TruValidate',
                         'AU10TIX',
                         'Veriff',
                         'Incode',
                         'Socotra',
                         'Akur8',
                         'Earnix',
                         'Shift Technology'],
 'ai_models_infrastructure': ['OpenAI',
                              'Anthropic',
                              'Google DeepMind',
                              'Cohere',
                              'Mistral AI',
                              'xAI',
                              'Meta',
                              'Perplexity',
                              'Fireworks AI',
                              'Together AI',
                              'Groq',
                              'Cerebras Systems',
                              'SambaNova Systems',
                              'Writer',
                              'Glean',
                              'Scale AI',
                              'Hugging Face',
                              'NVIDIA',
                              'DataRobot',
                              'H2O.ai',
                              'C3 AI',
                              'Palantir',
                              'Domino Data Lab',
                              'Weights & Biases',
                              'Pinecone',
                              'Weaviate',
                              'Zilliz',
                              'Anaconda',
                              'Runway',
                              'Dataminr',
                              'Snorkel AI',
                              'Labelbox',
                              'Abacus.AI',
                              'Adept AI',
                              'AI21 Labs',
                              'Stability AI',
                              'ElevenLabs',
                              'Synthesia',
                              'Harvey',
                              'Hebbia',
                              'Sierra',
                              'Decagon',
                              'Cognition',
                              'Abridge',
                              'PathAI',
                              'Tempus AI',
                              'Insitro',
                              'Recursion',
                              'EvolutionIQ',
                              'Tractable',
                              'Lightning AI',
                              'Replicate',
                              'Baseten',
                              'Modal',
                              'Anyscale',
                              'OctoAI',
                              'CoreWeave',
                              'Lambda',
                              'Crusoe',
                              'Vast Data',
                              'Graphcore',
                              'Nscale'],
 'data_cloud_analytics': ['Databricks',
                          'Snowflake',
                          'Dataiku',
                          'MongoDB',
                          'Confluent',
                          'Elastic',
                          'Cloudera',
                          'Alteryx',
                          'Informatica',
                          'Teradata',
                          'Celonis',
                          'UiPath',
                          'dbt Labs',
                          'Fivetran',
                          'Airbyte',
                          'Astronomer',
                          'Collibra',
                          'Atlan',
                          'Monte Carlo',
                          'BigID',
                          'DataStax',
                          'Starburst',
                          'Dremio',
                          'SingleStore',
                          'Neo4j',
                          'Redis',
                          'Cockroach Labs',
                          'ClickHouse',
                          'Timescale',
                          'MotherDuck',
                          'Hex',
                          'Sigma Computing',
                          'ThoughtSpot',
                          'Looker',
                          'Tableau',
                          'Power BI',
                          'Qlik',
                          'MicroStrategy',
                          'Sisense',
                          'Denodo',
                          'Precisely',
                          'Reltio',
                          'Talend',
                          'TIBCO',
                          'Boomi',
                          'MuleSoft',
                          'Matillion',
                          'Prefect',
                          'Dagster Labs',
                          'Aiven',
                          'PlanetScale',
                          'Supabase',
                          'Snowplow',
                          'Amplitude',
                          'Mixpanel',
                          'Heap',
                          'FullStory',
                          'Contentsquare',
                          'Pendo',
                          'Algolia',
                          'Coveo'],
 'banking_fintech_payments': ['FIS',
                              'Fiserv',
                              'Jack Henry',
                              'Temenos',
                              'nCino',
                              'Q2',
                              'Mambu',
                              'Thought Machine',
                              'Stripe',
                              'Block',
                              'Plaid',
                              'Adyen',
                              'Marqeta',
                              'Brex',
                              'Ramp',
                              'Affirm',
                              'SoFi',
                              'Upgrade',
                              'Blend',
                              'Enova',
                              'Mercury',
                              'EarnIn',
                              'GoCardless',
                              'Credit Karma',
                              'Robinhood',
                              'Chime',
                              'Klarna',
                              'Wise',
                              'Revolut',
                              'Checkout.com',
                              'PayPal',
                              'Toast',
                              'Nuvei',
                              'Worldpay',
                              'Global Payments',
                              'Alkami',
                              'Pagaya',
                              'Upstart',
                              'LendingClub',
                              'LendingTree',
                              'OppFi',
                              'Avant',
                              'Dave',
                              'Current',
                              'Varo Bank',
                              'Green Dot',
                              'Cross River',
                              'Coastal Community Bank',
                              'Column',
                              'Treasury Prime',
                              'Unit',
                              'Modern Treasury',
                              'Highnote',
                              'Lithic',
                              'Galileo',
                              'Synctera',
                              'Arc',
                              'Pipe',
                              'Fundbox',
                              'Bluevine',
                              'Kabbage',
                              'Square',
                              'Remitly',
                              'Flywire',
                              'Payoneer',
                              'AvidXchange',
                              'Bill.com',
                              'Tipalti',
                              'Airwallex',
                              'Nium',
                              'Rapyd',
                              'Circle',
                              'Coinbase',
                              'Kraken',
                              'Gemini',
                              'Ripple',
                              'Bakkt',
                              'Anchorage Digital',
                              'Fireblocks',
                              'MX',
                              'Yodlee',
                              'Envestnet',
                              'Broadridge',
                              'SS&C Technologies',
                              'Charles River Development',
                              'BlackLine'],
 'credit_bureaus_market_data': ['Experian',
                                'Equifax',
                                'TransUnion',
                                'LexisNexis Risk Solutions',
                                "Moody's",
                                'S&P Global',
                                'Fitch Ratings',
                                'Dun & Bradstreet',
                                'Verisk',
                                'CoreLogic',
                                'LSEG',
                                'Bloomberg',
                                'FactSet',
                                'MSCI',
                                'Morningstar',
                                'ICE',
                                'Nasdaq',
                                'CME Group',
                                'Cboe Global Markets',
                                'Broadridge',
                                'Refinitiv',
                                'PitchBook',
                                'CB Insights',
                                'Preqin',
                                'Kroll',
                                'Aon',
                                'Marsh McLennan',
                                'Willis Towers Watson',
                                'LexisNexis',
                                'RELX',
                                'Clarivate',
                                'Dow Jones',
                                'The Clearing House',
                                'Early Warning Services'],
 'consulting_system_integrators': ['Deloitte',
                                   'PwC',
                                   'EY',
                                   'KPMG',
                                   'Accenture',
                                   'McKinsey & Company',
                                   'Boston Consulting Group',
                                   'Bain & Company',
                                   'Booz Allen Hamilton',
                                   'Capgemini',
                                   'Cognizant',
                                   'Infosys',
                                   'Wipro',
                                   'Tata Consultancy Services',
                                   'HCLTech',
                                   'NTT DATA',
                                   'CGI',
                                   'Guidehouse',
                                   'Slalom',
                                   'West Monroe',
                                   'Oliver Wyman',
                                   'Kearney',
                                   'Roland Berger',
                                   'Alvarez & Marsal',
                                   'FTI Consulting',
                                   'Protiviti',
                                   'Publicis Sapient',
                                   'EPAM Systems',
                                   'Thoughtworks',
                                   'Globant',
                                   'Genpact',
                                   'ZS Associates',
                                   'Gartner',
                                   'Forrester',
                                   'BearingPoint',
                                   'PA Consulting',
                                   'Reply',
                                   'Endava',
                                   'Virtusa',
                                   'LTIMindtree',
                                   'Tech Mahindra',
                                   'Persistent Systems',
                                   'DXC Technology',
                                   'Avanade',
                                   'Hitachi Vantara',
                                   'Sopra Steria',
                                   'Capco',
                                   'The Hackett Group',
                                   'Grant Thornton',
                                   'BDO',
                                   'RSM US',
                                   'Crowe',
                                   'Mazars',
                                   'Baker Tilly',
                                   'IBM Consulting',
                                   'Kyndryl',
                                   'Perficient',
                                   'Insight Enterprises',
                                   'SoftServe',
                                   'DataArt',
                                   'Slalom Build',
                                   'WillowTree',
                                   'Valtech',
                                   'Kin + Carta',
                                   'Ciklum',
                                   'Nagarro',
                                   'Nexthink'],
 'banks_capital_markets': ['JPMorgan Chase',
                           'Bank of America',
                           'Wells Fargo',
                           'Citigroup',
                           'Goldman Sachs',
                           'Morgan Stanley',
                           'Capital One',
                           'U.S. Bank',
                           'PNC Financial Services',
                           'Truist',
                           'TD Bank',
                           'BMO Financial Group',
                           'Citizens Financial Group',
                           'Fifth Third Bank',
                           'KeyBank',
                           'Huntington Bank',
                           'Regions Bank',
                           'M&T Bank',
                           'Ally Financial',
                           'American Express',
                           'Synchrony',
                           'Navy Federal Credit Union',
                           'First Citizens Bank',
                           'State Street',
                           'BNY',
                           'Northern Trust',
                           'HSBC',
                           'Barclays',
                           'Deutsche Bank',
                           'UBS',
                           'Santander',
                           'BNP Paribas',
                           'Crédit Agricole',
                           'MUFG',
                           'Mizuho',
                           'SMBC',
                           'RBC',
                           'Scotiabank',
                           'CIBC',
                           'USAA',
                           'Charles Schwab',
                           'Fidelity Investments',
                           'Vanguard',
                           'BlackRock',
                           'T. Rowe Price',
                           'Franklin Templeton',
                           'Invesco',
                           'Nuveen',
                           'PIMCO',
                           'Jefferies',
                           'Lazard',
                           'Evercore',
                           'Raymond James',
                           'Interactive Brokers',
                           'Discover Financial Services',
                           'Comerica',
                           'First Horizon',
                           'Zions Bancorporation',
                           'Associated Bank',
                           'Synovus',
                           'Webster Bank',
                           'Wintrust',
                           'East West Bank',
                           'Frost Bank',
                           'New York Community Bank',
                           'Flagstar Bank',
                           'Valley Bank',
                           'Western Alliance Bank',
                           'Banc of California',
                           'Axos Bank',
                           'LendingClub Bank'],
 'insurance_insurtech': ['State Farm',
                         'Progressive',
                         'Allstate',
                         'Liberty Mutual',
                         'Nationwide',
                         'Travelers',
                         'GEICO',
                         'MetLife',
                         'Prudential Financial',
                         'AIG',
                         'Chubb',
                         'Zurich Insurance Group',
                         'AXA',
                         'Allianz',
                         'Munich Re',
                         'Swiss Re',
                         'The Hartford',
                         'CNA',
                         'Assurant',
                         'Unum',
                         'Principal Financial Group',
                         'Guardian Life',
                         'MassMutual',
                         'New York Life',
                         'Northwestern Mutual',
                         'Amica',
                         'Erie Insurance',
                         'Auto-Owners Insurance',
                         'Root Insurance',
                         'Lemonade',
                         'Oscar Health',
                         'Hippo',
                         'Coalition',
                         'Kin Insurance',
                         'Pie Insurance',
                         'NEXT Insurance',
                         'Clearcover',
                         'Snapsheet',
                         'Guidewire',
                         'Duck Creek Technologies',
                         'CCC Intelligent Solutions',
                         'Bold Penguin',
                         'Cover Genius',
                         'Policygenius',
                         'Gallagher',
                         'Brown & Brown'],
 'enterprise_software_security': ['Microsoft',
                                  'Google',
                                  'Amazon Web Services',
                                  'Oracle',
                                  'SAP',
                                  'IBM',
                                  'Salesforce',
                                  'ServiceNow',
                                  'Adobe',
                                  'Workday',
                                  'Atlassian',
                                  'Cisco',
                                  'Broadcom',
                                  'VMware',
                                  'Red Hat',
                                  'Dell Technologies',
                                  'Hewlett Packard Enterprise',
                                  'Lenovo',
                                  'Nutanix',
                                  'HashiCorp',
                                  'Cloudflare',
                                  'CrowdStrike',
                                  'Palo Alto Networks',
                                  'Okta',
                                  'Zscaler',
                                  'SentinelOne',
                                  'Splunk',
                                  'Datadog',
                                  'Dynatrace',
                                  'New Relic',
                                  'Twilio',
                                  'Zoom',
                                  'Box',
                                  'Dropbox',
                                  'DocuSign',
                                  'HubSpot',
                                  'Zendesk',
                                  'Five9',
                                  'Talkdesk',
                                  'Genesys',
                                  'NICE',
                                  'Pegasystems',
                                  'SAS',
                                  'Figma',
                                  'Canva',
                                  'Notion',
                                  'Airtable',
                                  'Asana',
                                  'monday.com',
                                  'Smartsheet',
                                  'Miro',
                                  'GitHub',
                                  'GitLab',
                                  'Vercel',
                                  'Netlify',
                                  'Samsara',
                                  'ServiceTitan',
                                  'Procore',
                                  'Autodesk',
                                  'Dassault Systèmes',
                                  'PTC',
                                  'Siemens Digital Industries Software',
                                  'Trimble',
                                  'OpenText',
                                  'Progress Software',
                                  'RingCentral',
                                  '8x8',
                                  'Avaya',
                                  'N-able',
                                  'Rapid7',
                                  'Tenable',
                                  'Qualys',
                                  'Proofpoint',
                                  'Mimecast',
                                  'CyberArk',
                                  'SailPoint',
                                  'OneTrust',
                                  'Varonis',
                                  'Rubrik',
                                  'Cohesity',
                                  'Veeam',
                                  'Commvault',
                                  'Pure Storage',
                                  'NetApp',
                                  'Infinidat'],
 'automotive_captive_finance': ['GM Financial',
                                'Ford Motor Credit',
                                'Toyota Financial Services',
                                'Honda Financial Services',
                                'Hyundai Capital America',
                                'Kia Finance America',
                                'Mercedes-Benz Financial Services',
                                'BMW Financial Services',
                                'Volkswagen Credit',
                                'Stellantis Financial Services',
                                'Nissan Motor Acceptance',
                                'Mazda Financial Services',
                                'Volvo Car Financial Services',
                                'Subaru Motors Finance',
                                'Tesla',
                                'Rivian',
                                'Lucid Motors',
                                'CarMax',
                                'Carvana',
                                'Cox Automotive',
                                'Santander Consumer USA',
                                'Credit Acceptance',
                                'Westlake Financial',
                                'Exeter Finance',
                                'OPENLANE',
                                'Cars.com',
                                'TrueCar',
                                'Autotrader',
                                'Edmunds']}

CATEGORY_PRIORITY = {'risk_fraud_identity': 1,
 'ai_models_infrastructure': 1,
 'banking_fintech_payments': 1,
 'credit_bureaus_market_data': 1,
 'automotive_captive_finance': 1,
 'data_cloud_analytics': 2,
 'consulting_system_integrators': 2,
 'banks_capital_markets': 2,
 'insurance_insurtech': 2,
 'enterprise_software_security': 2}

ATS_TOKEN_OVERRIDES = {'greenhouse': {'Talkdesk': 'talkdesk2',
                'DataDome': 'ddome',
                'Weights & Biases': 'wandb',
                'H2O.ai': 'h2oai'},
 'lever': {},
 'ashby': {}}


def slugify_company_name(name: str) -> str:
    """Create a reasonable first ATS-token guess from a company name."""

    ascii_name = (
        unicodedata.normalize("NFKD", name)
        .encode("ascii", "ignore")
        .decode("ascii")
        .lower()
    )
    return re.sub(r"[^a-z0-9]+", "", ascii_name)


def build_company_registry() -> dict[str, dict]:
    """Merge duplicate companies and retain every relevant category."""

    registry: dict[str, dict] = {}

    for category, names in COMPANY_GROUPS.items():
        priority = CATEGORY_PRIORITY.get(category, 3)

        for name in names:
            entry = registry.setdefault(
                name,
                {
                    "name": name,
                    "categories": [],
                    "priority": priority,
                    "candidate_token": slugify_company_name(name),
                },
            )

            if category not in entry["categories"]:
                entry["categories"].append(category)

            entry["priority"] = min(entry["priority"], priority)

    return dict(sorted(registry.items()))


COMPANY_REGISTRY = build_company_registry()


def get_ats_token(company_name: str, ats: str) -> str:
    """Return an ATS-specific token override or a normalized fallback token."""

    if company_name not in COMPANY_REGISTRY:
        raise KeyError(f"Unknown company: {company_name}")

    override = ATS_TOKEN_OVERRIDES.get(ats, {}).get(company_name)

    if override:
        return override

    return COMPANY_REGISTRY[company_name]["candidate_token"]


def build_ats_company_dict(
    ats: str,
    *,
    max_priority: int | None = None,
    categories: Iterable[str] | None = None,
) -> dict[str, str]:
    """
    Build the name-to-token dictionary consumed by an ATS collector.

    Set max_priority=1 to run only the highest-priority companies.
    Pass categories to restrict a run to selected company groups.
    """

    selected_categories = set(categories or [])
    companies: dict[str, str] = {}

    for company_name, metadata in COMPANY_REGISTRY.items():
        if max_priority is not None and metadata["priority"] > max_priority:
            continue

        if selected_categories and not selected_categories.intersection(
            metadata["categories"]
        ):
            continue

        companies[company_name] = get_ats_token(company_name, ats)

    return companies


# All collectors reference the same company universe.
GREENHOUSE_COMPANIES = build_ats_company_dict("greenhouse")
LEVER_COMPANIES = build_ats_company_dict("lever")
ASHBY_COMPANIES = build_ats_company_dict("ashby")

# Backward compatibility with the current collect_greenhouse.py file.
COMPANIES = GREENHOUSE_COMPANIES


if __name__ == "__main__":
    print(f"Master companies: {len(COMPANY_REGISTRY)}")
    print(f"Greenhouse candidates: {len(GREENHOUSE_COMPANIES)}")
    print(f"Priority-one companies: {len(build_ats_company_dict('greenhouse', max_priority=1))}")
